### Data processing 

# Hoyles 2018
library(datapasta)

df_paste()

metabolites_pure_culture = data.table(data.frame(stringsAsFactors=FALSE, V1 = c("Escherichia coli L6-FAA1", "Escherichia coli L24-FAA5",
                                                                                "Escherichia coli L9-MRS1",
                                                                                "Escherichia coli L19-FAA2",
                                                                                "Hafnia paralvei L15-FAA9",
                                                                                "Escherichia coli L13-FAA2",
                                                                                "Escherichia coli L16-FAA5",
                                                                                "Escherichia coli L20-FAA3",
                                                                                "Escherichia coli L1-FAA5",
                                                                                "Citrobacter koseri L8-FAA3",
                                                                                "Escherichia coli L5-FAA2",
                                                                                "Citrobacter gillenii L26-FAA1",
                                                                                "Escherichia coli D3(8)",
                                                                                "Escherichia coli D2(8)",
                                                                                "Escherichia coli D2(2)",
                                                                                "Escherichia coli D1(2)",
                                                                                "Escherichia coli D4(15)",
                                                                                "Escherichia coli D2(1)",
                                                                                "Escherichia coli D5(1)",
                                                                                "Klebsiella pneumoniae subsp. pneumoniae L4-FAA5",
                                                                                "Clostridium sporogenes D1(9)",
                                                                                "[Clostridium] bifermentans D4(1)",
                                                                                "Clostridium perfringens L20-BSM1",
                                                                                "Enterococcus gallinarum D6(5)",
                                                                                "Bacteroides vulgatus L9-FAA7",
                                                                                "Enterococcus faecalis D5(2)",
                                                                                "Parabacteroides johnsonii L13-FAA10",
                                                                                "Bacteroides fragilis L6-FAA7",
                                                                                "Enterococcus faecalis D3(1)",
                                                                                "Bacteroides vulgatus D1(4)",
                                                                                "Clostridium paraputrificum L16-FAA6",
                                                                                "Enterococcus faecalis D2(14)",
                                                                                "[Clostridium] ramosum L16-FAA1",
                                                                                "Streptococcus sanguinis L4-MRS1",
                                                                                "Streptococcus anginosus D5(12)",
                                                                                "Streptococcus anginosus D1(5)",
                                                                                "Bifidobacterium breve LCR5",
                                                                                "Staphylococcus hominis D2(4)",
                                                                                "Enterococcus faecium D6(1)",
                                                                                "Bifidobacterium infantis DSM 20088T",
                                                                                "Streptococcus vestibularis L26-MRS7",
                                                                                "Bifidobacterium bifidum LCR11",
                                                                                "Lactobacillus fermentum L26-MRS5",
                                                                                "Bifidobacterium longum LCR6",
                                                                                "Bifidobacterium longum DSM 20219T",
                                                                                "Bifidobacterium longum subsp. infantis LCR2",
                                                                                "Streptococcus oralis L4-MRS5",
                                                                                "Streptococcus sp. D4(3)",
                                                                                "Streptococcus gallolyticus L25-MRS1",
                                                                                "Bifidobacterium pseudocatenulatum LCR3",
                                                                                "Pseudomonas aeruginosa L1-FAA6",
                                                                                "Lactobacillus rhamnosus L26-FAA6",
                                                                                "Bifidobacterium animalis subsp. lactis L26-MRS4",
                                                                                "Bifidobacterium longum subsp. longum L19-MRS1",
                                                                                "Unknown Bifidobacterium LCR4",
                                                                                "Bifidobacterium breve LCR8",
                                                                                "Bifidobacterium longum subsp. longum L25-MRS8",
                                                                                "Bifidobacterium bifidum L25-MRS2",
                                                                                "Bifidobacterium dentium LCR1",
                                                                                "[Clostridium] innocuum D2(9)",
                                                                                "Bifidobacterium adolescentis DSM 20083T",
                                                                                "Bifidobacterium animalis subsp. lactis LCR26",
                                                                                "Actinomyces odontolyticus L12-BSM1",
                                                                                "Fusobacterium ulcerans L9-FAA5",
                                                                                "Bifidobacterium gallicum DSM 20093T",
                                                                                "Actinomyces viscosus L6-BSM10"),
                                                 V2 = c("Enterobacteriaceae, Proteobacteria", "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Enterobacteriaceae,
                                                        Proteobacteria",
                                                        "Clostridiaceae (Cluster I),
                                                        Firmicutes",
                                                        "Peptostreptococcaceae,
                                                        Firmicutes",
                                                        "Clostridiaceae (Cluster I),
                                                        Firmicutes",
                                                        "Enterococcaceae, Firmicutes",
                                                        "Bacteroidaceae,
                                                        Bacteroidetes",
                                                        "Enterococcaceae,
                                                        Firmicutes",
                                                        "Porphyromonadaceae,
                                                        Bacteroidetes",
                                                        "Bacteroidaceae,
                                                        Bacteroidetes",
                                                        "Enterococcaceae, Firmicutes",
                                                        "Bacteroidaceae,
                                                        Bacteroidetes",
                                                        "Clostridiaceae (Cluster I), Firmicutes",
                                                        "Enterococcaceae, Firmicutes",
                                                        "Erysipelotrichaceae,
                                                        Firmicutes",
                                                        "Streptococcaceae,
                                                        Firmicutes",
                                                        "Streptococcaceae,
                                                        Firmicutes",
                                                        "Streptococcaceae,
                                                        Firmicutes",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Staphylococcaceae,
                                                        Firmicutes",
                                                        "Enterococcaceae,
                                                        Firmicutes",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Streptococcaceae,
                                                        Firmicutes",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Lactobacillaceae,
                                                        Firmicutes",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Streptococcaceae,
                                                        Firmicutes",
                                                        "Streptococcaceae,
                                                        Firmicutes",
                                                        "Streptococcaceae,
                                                        Firmicutes",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Pseudomonadaceae,
                                                        Proteobacteria",
                                                        "Lactobacillaceae, Firmicutes",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Erysipelotrichaceae, Firmicutes",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Actinomycetaceae,
                                                        Actinobacteria",
                                                        "Fusobacteriaceae,
                                                        Fusobacteria",
                                                        "Bifidobacteriaceae,
                                                        Actinobacteria",
                                                        "Actinomycetaceae,
                                                        Actinobacteria"),
                                                 V3 = c(53.94, 53.94, 52.94, 51.94, 45.44, 44.94, 44.94, 43.94, 42.94,
                                                        42.24, 41.94,
                                                        37.94, 32.64,
                                                        31.84, 31.54,
                                                        30.34, 29.94,
                                                        24.44, 22.94,
                                                        14.94, 4.64, 3.72,
                                                        2.19, 1.74,
                                                        1.7, 1.64, 1.42,
                                                        1.42, 1.24,
                                                        1.08, 1.04, 1,
                                                        0.94, 0.49, 0.48,
                                                        0.44, 0.38,
                                                        0.34, 0.31, 0.27,
                                                        0.25, 0.24,
                                                        0.22, 0.22, 0.2,
                                                        0.18, 0.16,
                                                        0.16, 0.14, 0.14,
                                                        0.12, 0.12, 0.1,
                                                        0.09, 0.07,
                                                        0.05, 0.05, 0.05,
                                                        0.04, 0.03,
                                                        0.02, 0.02, 0.02,
                                                        0.02, 0.01,
                                                        0),
                                                 V4 = c(0.03, 0.04, 0.02, 0.03, 0.03, 0.03, 0.03, 0.04, 0.03, 0.02,
                                                        0.02, 0.03,
                                                        0.04, 0.03,
                                                        0.03, 0.03, 0.03,
                                                        0.05, 0.04,
                                                        0.02, 0.12, 0,
                                                        0.03, 0.04, 0,
                                                        0.05, 0, 0, 0.06,
                                                        0.02, 0.03,
                                                        0.05, 0.07, 0.03,
                                                        0.02, 0.03,
                                                        0.03, 0.03, 0.06,
                                                        0.02, 0.02,
                                                        0.02, 0.02, 0.02,
                                                        0.02, 0.03,
                                                        0.02, 0.03, 0.04,
                                                        0.03, 0.02,
                                                        0.03, 0.02, 0.02,
                                                        0.02, 0.02,
                                                        0.02, 0.02, 0.02,
                                                        0.03, 0.02,
                                                        0.02, 0.02, 0.02,
                                                        0.01, 0),
                                                 V5 = c(0.03, 0.07, 0.08, 0.03, 0.08, 0, 0.06, 0.07, 0.03, 0.35, 0.07,
                                                        0.13, 0.03,
                                                        0.02, 0.01, 0,
                                                        0.03, 0, 0,
                                                        0.41, 1.03, 1.08,
                                                        0.23, 0.3, 0.88,
                                                        0.45, 0.65,
                                                        0.51, 0.29, 0.71,
                                                        0.33, 0.17,
                                                        0.33, 0.02, 0.16,
                                                        0.11, 0.04,
                                                        0.33, 0.13, 0.04,
                                                        0, 0.02, 0.16,
                                                        0.02, 0.02,
                                                        0.02, 0, 0.06, 0,
                                                        0.01, 0.04,
                                                        0.02, 0.01, 0.01,
                                                        0.01, 0.01,
                                                        0.02, 0.01, 0.02,
                                                        0.01, 0.01,
                                                        0.01, 0.01, 0.02,
                                                        0.01, 0),
                                                 V6 = c(0.05, 0.05, 0.04, 0.05, 0.07, 0.04, 0.05, 0.07, 0.05, 0.04,
                                                        0.03, 0.06,
                                                        0.08, 0.06,
                                                        0.06, 0.07, 0.06,
                                                        0.08, 0.05,
                                                        0.05, 0.07, 0,
                                                        0.06, 0.15, 0,
                                                        0.13, 0, 0, 0.16,
                                                        0.01, 0.07,
                                                        0.14, 0.09, 0.06,
                                                        0.12, 0.14, 0,
                                                        0.08, 0.14, 0,
                                                        0.05, 0.01,
                                                        0.03, 0.01, 0,
                                                        0.01, 0.05, 0.13,
                                                        0.06, 0.02, 0,
                                                        0, 0, 0.01, 0,
                                                        0, 0.01, 0.01,
                                                        0, 0, 0, 0, 0,
                                                        0, 0, 0),
                                                 V7 = c(28.17, 27.67, 27.17, 24.17, 23.97, 23.47, 23.17, 24.17, 23.67,
                                                        21.17, 23.17,
                                                        18.77, 16.77,
                                                        16.47, 16.27,
                                                        16.17, 14.67,
                                                        11.67, 12.37,
                                                        10.17, 17.37,
                                                        12.15, 1.97, 0,
                                                        2.65, 0, 1.51,
                                                        2.67, 0, 1.66,
                                                        1.37, 0, 1.47, 0,
                                                        0, 0, 32.04,
                                                        1.47, 0, 27.56,
                                                        0, 33.14, 0.47,
                                                        23.86, 27.92,
                                                        25.11, 0, 0, 0,
                                                        28.26, 0.09,
                                                        0.16, 6.76,
                                                        14.86, 8.51, 13.11,
                                                        5.87, 1.32,
                                                        2.18, 0.26, 1.85,
                                                        1.26, 0.82,
                                                        0.14, 0.31, 0.04),
                                                 V8 = c(0.7, 0.56, 0.6, 0.6, 5.2, 0.6, 0.6, 0.7, 0.6, 0.74, 0.6, 0.6,
                                                        6.8, 8.2, 8,
                                                        8.6, 6.75, 8.7,
                                                        6.7, 0.52,
                                                        16.9, 0, 0.81,
                                                        0.77, 0, 0.67, 0,
                                                        0, 0.74, 2.82,
                                                        0.63, 0.69,
                                                        0.6, 0.6, 0.6,
                                                        0.64, 26.51, 2.3,
                                                        0.7, 29.81,
                                                        0.4, 33.91, 1.5,
                                                        23.77, 23.19, 0,
                                                        0.6, 0.56,
                                                        0.6, 19.68, 0, 0,
                                                        6.32, 12.64,
                                                        6.84, 6.33, 9.4,
                                                        1.72, 1.75, 0,
                                                        2.31, 1.75, 0,
                                                        1.46, 0.33,
                                                        0.22),
                                                 V9 = c(7.64, 7.14, 9.14, 7.64, 6.44, 8.64, 9.64, 12.64, 10.64, 10.64,
                                                        10.64, 12.64,
                                                        6.14, 6.74,
                                                        6.34, 5.44, 6.64,
                                                        4.14, 5.14,
                                                        7.14, 16.24,
                                                        8.81, 10.64, 1.24,
                                                        0, 0.82, 0, 0,
                                                        1.24, 0.06,
                                                        1.04, 1.34, 1.34,
                                                        0.34, 0.09,
                                                        0.06, 2, 0.08,
                                                        0.3, 0.34, 0.28,
                                                        0.5, 0.19, 0.39,
                                                        0.58, 0.38,
                                                        1.39, 0.25, 0.09,
                                                        0.78, 0.03,
                                                        0.11, 0.1, 0.22,
                                                        0.06, 0.14,
                                                        0.09, 0.06, 0.04,
                                                        0.04, 0.02,
                                                        0.01, 0, 0.07,
                                                        0.02, 0.03),
                                                 V10 = c(8.2, 4, 10.2, 9.8, 14.6, 10, 9.3, 9, 9, 11, 9.7, 11, 6.9, 7,
                                                         6.8, 8, 6.4,
                                                         7.6, 6.4, 12,
                                                         13.5, 0, 5.3,
                                                         0.83, 0, 1.04, 0,
                                                         0, 1.02, 0,
                                                         2.5, 1.4, 1.8,
                                                         0.33, 0.46, 0.38,
                                                         0.89, 0.32,
                                                         0.37, 0.21, 0.65,
                                                         0.49, 0.8,
                                                         0.06, 0.28, 0.02,
                                                         0.8, 0.4, 0.35,
                                                         0.27, 0, 0,
                                                         0.01, 0.13, 0, 0,
                                                         0.05, 0.07,
                                                         0.01, 0, 0.01,
                                                         0.06, 0, 0, 0,
                                                         0),
                                                 V11 = c(0.19, 2.4, 0, 0.02, 0.8, 0, 0.06, 0.15, 0.03, 5.3, 0.32, 4.6,
                                                         0, 0, 0, 0,
                                                         0.2, 0, 0, 4.4,
                                                         0.1, 0.03, 4.8,
                                                         29.8, 0, 27.8,
                                                         0.24, 0.56,
                                                         28.6, 0.12, 2,
                                                         27.2, 4.3, 22.9,
                                                         29.3, 29.1,
                                                         12.77, 2.5, 30.8,
                                                         12.01, 29.4,
                                                         14.13, 0.7,
                                                         10.47, 13.51, 11.65,
                                                         24.6, 27.9,
                                                         31.2, 12.66, 0,
                                                         12.49, 3.12,
                                                         6.79, 4.1, 6.07,
                                                         2.63, 0.34,
                                                         0.88, 0.1, 0.92,
                                                         0.39, 0.02, 0,
                                                         0.06, 0),
                                                 V12 = c(5.1, 6, 4.7, 4.8, 2.5, 4.5, 4.8, 6.5, 5.2, 5, 4.1, 5.4, 8.7,
                                                         8.5, 9.5,
                                                         9.4, 7.3, 9, 7,
                                                         5.9, 0.9, 0, 5.9,
                                                         2, 0, 1.6, 0,
                                                         0, 2, 0.33,
                                                         3.6, 1.8, 5.2,
                                                         9.2, 2, 2.2, 0.68,
                                                         4, 1.95, 0.94,
                                                         2.2, 0.91,
                                                         2.7, 0.77, 0.83,
                                                         0.74, 5.1, 1.9,
                                                         2.2, 1.25, 0,
                                                         0, 2.73, 3.06,
                                                         3.75, 3.49,
                                                         4.68, 0.9, 1.14, 0,
                                                         1.57, 0.79, 0,
                                                         0.1, 0.43,
                                                         0.06)
                                                 ))
setnames(metabolites_pure_culture, c("Species", "Family", "TMA", "TMA_1", "DMA", "DMA_1", "acetate", "acetate_1", "ethanol", "ethanol_1", "lactate", "lactate_1"))

#_1 = presence of TMAO

df_paste()

species_data_batch = data.table(data.frame(stringsAsFactors=FALSE,
                                           SampleTime = c("A0", "A4", "A9", "B0", "B4", "B9", "C0", "C4", "C9",
                                                                 "D0", "D4", "D9",
                                                                 "E0", "E4", "E9", "F0",
                                                                 "F4", "F9"),
                                           EUB338 = c(9.08, 8.89, 9.13, 8.97, 8.99, 9.25, 9.03, 8.76, 9.05,
                                                      8.97, 8.89, 9.12,
                                                      9.26, 9.15, 9.07, 9.22,
                                                      9.23, 9.24),
                                           Bac303 = c(7.78, 7.7, 7.9, 7.81, 7.8, 7.92, 7.65, 7.56, 7.57,
                                                      7.63, 7.66, 7.73,
                                                      8.23, 7.65, 7.63, 8.2,
                                                      7.98, 7.34),
                                           Ato291 = c(6.96, 7.4, 7.48, 6.95, 7.43, 7.63, 7.14, 7.64, 7.54,
                                                      7.3, 7.8, 7.65, 7.35,
                                                      8.04, 7.8, 7.45, 8.21,
                                                      8.3),
                                           Bif164 = c(7.17, 7.64, 8.04, 7.26, 7.57, 8.17, 7.19, 7.81, 8.33,
                                                      7.31, 8.12, 8.26,
                                                      7.55, 7.66, 8.26, 7.54,
                                                      8.16, 8.32),
                                           Ent = c(5.65, 7.36, 8.1, 5.65, 7.01, 7.4, 5.8, 6.64, 8.17,
                                                   5.43, 5.95, 7.33,
                                                   6.82, 7.28, 8.07, 6.94,
                                                   6.76, 7.28),
                                           Bet42a = c(8.22, 7.32, 6.1, 8.22, 7.37, 6.18, 8.29, 6.35, 5.99,
                                                      8.27, 6.3, 6.18,
                                                      7.88, 7.51, 7.49, 7.94,
                                                      7.39, 7.4),
                                           Prop853 = c(7.68, 7.44, 7.62, 7.69, 7.62, 7.63, 7.74, 7.74, 7.76,
                                                       7.69, 7.71, 7.77,
                                                       7.25, 7.63, 8.03, 7.37,
                                                       7.73, 8.04),
                                           Lab158 = c(6.7, 7.04, 6.92, 6.93, 7.2, 6.98, 6.67, 6.81, 6.21,
                                                      6.76, 6.47, 5.99,
                                                      7.29, 6.69, 7, 7.28, 6.6,
                                                      7.16),
                                           Fpra655 = c(7.36, 7.41, 7.24, 7.45, 7.43, 7.42, 7.25, 7.31, 6.89,
                                                       7.29, 7.29, 6.98,
                                                       7.29, 8.05, 8.06, 7.39,
                                                       7.45, 7.42),
                                           Erec482 = c(8.52, 8.2, 7.98, 8.54, 8.26, 8.11, 7.7, 7.73, 7.75,
                                                       7.67, 7.77, 7.76,
                                                       7.77, 7.78, 7.97, 7.78,
                                                       7.92, 8.21),
                                           Clit135 = c(6.21, 5.65, 5.25, 5.99, 5.65, 4.95, 5.43, 4.95, 5.25,
                                                       5.56, 5.25, 5.25,
                                                       5.8, 6.23, 6.1, 5.56,
                                                       6.28, 5.95),
                                           Rbro_Rfla = c(7.44, 7.46, 7.39, 7.49, 7.42, 7.4, 7.3, 7.34, 7.36,
                                                         7.44, 7.53, 7.31,
                                                         7.43, 7.47, 7.47, 7.34,
                                                         7.48, 7.51),
                                           Chis150 = c(7.05, 7.34, 7.3, 6.84, 7.08, 7.27, 6.07, 7.22, 7.41,
                                                       5.95, 6.5, 7.49,
                                                       6.68, 7.29, 7.38, 6.58,
                                                       7.14, 7.39)
))

df_paste()

metabolites_batch = data.table(data.frame(stringsAsFactors=FALSE,
                                          SampleTime = c("A0", "A4", "A9", "B0", "B4", "B9", "C0", "C4", "C9",
                                                               "D0", "D4", "D9", "E0",
                                                               "E4", "E9", "F0", "F4",
                                                               "F9"),
                                          TMA = c(0.03, 0.77, 5.46, 0.03, 0.03, 0.06, 0.02, 0.16, 6.33,
                                                  0.03, 0.03, 0.06, 0.03,
                                                  1.61, 10.81, 0.03, 0.05,
                                                  0.08),
                                          TMAO = c(89.45, 92.3, 71.4, 0.58, 0.56, 0.21, 80, 81.1, 76.83,
                                                   0.62, 0.55, 0.2, 79.6,
                                                   80, 70.8, 0.58, 0.23,
                                                   0.05),
                                          DMA = c(0.05, 0.45, 0.86, 0.04, 0.03, 0.05, 0.04, 0.19, 0.4,
                                                  0.05, 0.03, 0.04, 0.05,
                                                  0.61, 1.4, 0.05, 0.05,
                                                  0.16),
                                          Ethanol = c(0.44, 0.59, 1.76, 0.31, 0.92, 2.14, 0.4, 0.55, 2.07,
                                                      0.31, 0.69, 2.01, 0.41,
                                                      1.52, 2.5, 0.27, 2.78,
                                                      2.76),
                                          Acetate = c(1.63, 6.68, 26.51, 1.51, 9.79, 33.5, 0.89, 4.61, 33.7,
                                                      0.97, 6.41, 32.4, 1.76,
                                                      17.5, 38.5, 1.77, 29.5,
                                                      38.3),
                                          Lactate = c(1.44, 3.69, 13.61, 1.42, 4.53, 12, 1.44, 2.96, 15.51,
                                                      1.5, 3.74, 13.94, 1.4,
                                                      7.38, 10.7, 1.37, 9.75,
                                                      3.95)))

vector_paste()

species_probes = data.table(data.frame(stringsAsFactors = F, SpeciesID = 
                                         c("Ato291", "Bac303", "Bet42a", "Bif164", "Chis150", "Clit135", "Ent", "Erec482", "Eub338/Eub338II/Eub338III‡", "Fpra655", "Lab158", "Prop853", "Rbro730/Rfla729‡"),
                                       SpeciesCat = 
                                         c("Cryptobacterium curtum, Gordonibacter pamelaeae, Paraeggerthella hongkongensis, all Eggerthella, Collinsella, Olsenella and Atopobium species; ‘Enorma’ and Senegalemassilia spp. (most members of the class Coriobacteriia; phylum Actinobacteria)", "Most members of the genus Bacteroides, some Parabacteroides and Prevotella species, Paraprevotella, Xylanibacter, Barnesiella species and Odoribacter splanchnicus (order Bacteroidales; phylum Bacteroidetes)", "Betaproteobacteria (class Betaproteobacteria; phylum Proteobacteria)", "Most Bifidobacterium species and Parascardovia denticolens (family Bifidobacteriaceae; phylum Actinobacteria)", "Most members of Clostridium cluster I, all members of Clostridium cluster II (family Clostridiaceae; phylum Firmicutes)", "Nine members of [Clostridium] cluster XI, including [Clostridium] difficile (family Peptostreptococcaceae; phylum Firmicutes)", "Enterobacteriaceae except Proteus spp. (order Gammaproteobacteria; phylum Proteobacteria)", "Most members of Clostridium cluster XIVa (family Lachnospiraceae; phylum Firmicutes)", "Bacteria", "Faecalibacterium prausnitzii and Subdoligranulum spp. (Clostridium cluster IV; family Ruminococcaceae; phylum Firmicutes)", "All Oenococcus, Vagococcus, Melissococcus, Tetragenococcus, Enterococcus, Catellicoccus, Paralactobacillus, Pediococcus and Lactococcus species, most Lactobacillus, Weissella and Leuconostoc species (order Lactobacillales; phylum Firmicutes)", "Most members of Clostridium cluster IX (family Veillonellaceae; phylum Firmicutes)", "Anaerotruncus colihominis, Ruminococcus bromii, Ruminococcus flavefaciens, Ruminococcus albus, Desulfotomaculum alcoholivorax (Clostridium cluster IV; family Ruminococcaceae; phylum Firmicutes)")
                                       ))

metabolites_pure_culture = melt(metabolites_pure_culture, id.vars = c("Species", "Family"))
metabolites_pure_culture[,TMAOMedia:=ifelse(grepl("_1", variable), "TMAO+", "TMAO-")]
metabolites_pure_culture[,Metabolite:=gsub("_1", "", variable)]
ggplot(metabolites_pure_culture, aes(x=TMAOMedia, y = value)) + geom_boxplot() + geom_jitter(width = 0.5, aes(color = Family)) + facet_wrap(~Metabolite, scales = "free")

metabolites_pure_culture[,Family:=gsub("\\,.*", "", Family)]
metabolites_pure_culture[,ZScore:=scale(value), by=Metabolite]
metabolites_pure_culture[,ZScoreMedia:=scale(value), by=list(Metabolite, TMAOMedia)]
metabolites_pure_culture[,list(length(unique(Species[ZScoreMedia > 1.5])), length(unique(Species[ZScore > 1.5]))), by=Metabolite]
#Some different species added

metabolites_pure_compare = dcast(metabolites_pure_culture, Species+Metabolite~TMAOMedia, value.var = "value")
ggplot(metabolites_pure_compare, aes(x=`TMAO+`, y = `TMAO-`)) + geom_point() + facet_wrap(~Metabolite, scales = "free")
ggplot(metabolites_pure_compare, aes(x=rank(`TMAO+`), y = rank(`TMAO-`))) + geom_point() + facet_wrap(~Metabolite, scales = "free")

#Generally a correlation among the highest producers except for TMA/DMA

#true_contribs = metabolites_pure_culture[ZScore > 1.5, list(Species, value, TMAOMedia, ZScore), by=Metabolite]

# How are we runnign MIMOSA?
species_dat = melt(species_data_batch, id.var ="SampleTime", variable.name = "SpeciesID")
